CREATE TABLE inventory_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    qr_code VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    organization VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity >= 0),
    last_used VARCHAR(255),
    shared BOOLEAN NOT NULL DEFAULT FALSE,
    checked_out BOOLEAN NOT NULL DEFAULT FALSE,
    borrow_count INTEGER DEFAULT 0,
    checkout_purpose VARCHAR(255),
    checkout_due_date DATE,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE
);
